#!/bin/bash
# Setup instructions for Email Capture & Analytics System

echo "📊 EMAIL CAPTURE & ANALYTICS SYSTEM - SETUP"
echo "=============================================="
echo ""
echo "✅ What's been set up:"
echo "  1. ExitPopup now sends emails to Google Sheets"
echo "  2. Analytics system tracks visitor behavior"
echo "  3. Session-based tracking for each visitor"
echo ""
echo "⏭️ NEXT STEPS (5 minutes):"
echo ""
echo "1️⃣  Open .env.local"
echo "   Add: NEXT_PUBLIC_GOOGLE_SHEETS_WEBHOOK=https://script.google.com/macros/d/YOUR_ID/useweb"
echo ""
echo "2️⃣  Create Google Apps Script webhook"
echo "   👉 Follow instructions in: src/app/docs/QUICK_START.md"
echo ""
echo "3️⃣  Restart dev server"
echo "   Ctrl+C then npm run dev"
echo ""
echo "4️⃣  Test:"
echo "   - Open site"
echo "   - Trigger exit popup (close tab/back button)"
echo "   - Submit email"
echo "   - Email appears in Google Sheets ✅"
echo ""
echo "📚 Full documentation:"
echo "   - src/app/docs/QUICK_START.md (5-min setup)"
echo "   - src/app/docs/GOOGLE_SHEETS_SETUP.js (detailed)"
echo "   - src/app/docs/TRACKING_PLAN.md (strategy)"
echo ""
echo "📊 Files created:"
echo "   - src/app/utils/analytics.js (event tracking)"
echo "   - src/app/utils/googleSheets.js (sheets integration)"
echo "   - ExitPopup.js updated (now sends to Google Sheets)"
echo ""
echo "Happy tracking! 🚀"
